version: "3.4"

# To run mysql as part of Docker
services:
  php:
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-api-platform}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-api}?serverVersion=${MYSQL_VERSION:-8}

###> doctrine/doctrine-bundle ###
  database:
      image: mysql:8
      deploy:
        restart_policy:
          condition: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-!ChangeMeRoot!}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-api}
        MYSQL_USER: ${MYSQL_USER:-api-platform}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      volumes:
        - db_data:/var/lib/mysql:rw
      ports:
        - 3306:3306
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###
